# Generated by Django 4.1.1 on 2022-11-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='attached',
            new_name='avatar',
        ),
    ]
