# Generated by Django 4.1.1 on 2022-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_comments',
            field=models.ManyToManyField(related_name='disliked_comments', to='red.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_posts',
            field=models.ManyToManyField(related_name='disliked_posts', to='red.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_comments',
            field=models.ManyToManyField(related_name='liked_comments', to='red.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_posts', to='red.post'),
        ),
    ]
