# Generated by Django 4.1.1 on 2022-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_rename_attached_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
