# Generated by Django 4.1.1 on 2022-11-16 10:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0003_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid hex color', regex='^[a-f0-9]{6}$')])),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flairs', to='red.sub')),
            ],
        ),
    ]
