# Generated by Django 4.1.1 on 2023-01-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0004_remove_comment_points_remove_post_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
