# Generated by Django 4.1.1 on 2022-11-17 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0006_alter_flair_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flair',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid hex color', regex='^[a-fA-F0-9]{6}')]),
        ),
    ]
