# Generated by Django 4.1.1 on 2022-11-17 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0007_alter_flair_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Sub name must be alphanumeric.', regex='^[0-9a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator(code='nomatch', message='Invalid email')]),
        ),
    ]
