# Generated by Django 4.1.1 on 2022-11-19 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0008_alter_sub_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flair',
            new_name='PostFlair',
        ),
        migrations.AddField(
            model_name='post',
            name='flair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='red.postflair'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='UserFlair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid hex color', regex='^[a-fA-F0-9]{6}')])),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userflairs', to='red.sub')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='flairs',
            field=models.ManyToManyField(to='red.userflair'),
        ),
    ]
