# Generated by Django 4.1.1 on 2023-01-29 20:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0008_alter_user_username_linkopenedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkopenedrequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='linkopenedrequest',
            name='url',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='slug', unique=True),
        ),
    ]
