# Generated by Django 4.1.1 on 2023-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0009_linkopenedrequest_purpose_linkopenedrequest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkopenedrequest',
            name='purpose',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='linkopenedrequest',
            name='url',
            field=models.SlugField(max_length=86, unique=True),
        ),
    ]
