# Generated by Django 4.1.1 on 2022-11-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0010_comment_deleted_post_deleted_postflair_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postflair',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postflairs', to='red.sub'),
        ),
    ]
