# Generated by Django 4.1.1 on 2022-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0011_alter_postflair_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
