# Generated by Django 4.1.1 on 2023-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0011_user_saved_comments_user_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='description',
            field=models.CharField(default='No description.', max_length=64),
        ),
    ]
