# Generated by Django 4.1.1 on 2023-05-07 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0012_sub_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('title', models.CharField(max_length=48)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='rules',
            field=models.ManyToManyField(related_name='subrules', to='red.subrule'),
        ),
    ]
