# Generated by Django 4.1.1 on 2022-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0013_alter_comment_deleted_alter_post_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='deleted',
        ),
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='postflair',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userflair',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
