# Generated by Django 4.1.1 on 2023-05-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0013_subrule_sub_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrule',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='red.post')),
                ('rule_broken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.subrule')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.sub')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='red.comment')),
                ('rule_broken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.subrule')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.sub')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
