# Generated by Django 4.1.1 on 2022-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0014_remove_sub_deleted_post_edited_postflair_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='postflair',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userflair',
            name='deleted',
        ),
    ]
