# Generated by Django 4.1.1 on 2022-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0015_remove_comment_deleted_remove_post_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='postflair',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userflair',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
