# Generated by Django 4.1.1 on 2022-11-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0017_remove_postflair_deleted_remove_postflair_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='edited',
        ),
    ]
