# Generated by Django 4.1.1 on 2022-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0019_comment_edited_post_edited_user_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
