# Generated by Django 4.1.1 on 2022-11-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0020_post_nsfw_post_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='mods',
            field=models.ManyToManyField(to='red.user'),
        ),
        migrations.AddField(
            model_name='sub',
            name='pinned_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='red.post'),
        ),
    ]
